### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by ktaneja** [ict-spitfire/ld4sensors#2]
After fixing the POM dependencies and buildpath 

I am getting compilation problems in the source where the signature of methods don't match.

The method addUom(Resource, String) in the type LD4SDataResource is not applicable for the arguments (Resource, String, OntModel)   LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 101

Description Resource    Path    Location    Type
The method addObsProp(Resource, String, ObjectProperty, String, OntModel) is undefined for the type LD4STypeResource    LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 92 Java Problem
The method addUom(Resource, String) in the type LD4SDataResource is not applicable for the arguments (Resource, String, OntModel)   LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 101    Java Problem
The method crossResourcesAnnotation(LD4SObject, Resource) in the type LD4SDataResource is not applicable for the arguments (Type, Resource, OntModel)   LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 129    Java Problem
The method makeOVData() is undefined for the type TypeResource  TypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 211    Java Problem
The method makeOVData() is undefined for the type TypeResource  TypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 156    Java Problem
The method makeOVData() is undefined for the type LD4STypeResource  LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 39 Java Problem
The method addLinkedData(Resource, Context.Domain, Context) in the type LD4SDataResource is not applicable for the arguments (Resource, Context.Domain, Context, OntModel)  TypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 61 Java Problem
Type mismatch: cannot convert from Model to OntModel    TypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 55 Java Problem
The method createOVResource() of type LD4STypeResource must override or implement a supertype method    LD4STypeResource.java   /ld4sensors/src/main/java/eu/spitfire_project/ld4s/resource/type    line 55 Java Problem

Thanks,
Kunal

**Comment by iammyr** [comment]
Hi Kunal, 

thanks a million for raising the issue. Could you please refer to the version at https://github.com/iammyr/ld4sensors which is more up to date? 

Also, the lib folder contains all the libraries necessary to run the service. Please, refer to those when configuring your build path rather than using Maven cause even if you fixed the pom.xml you may be referring to wrong versions of the libraries. 

Thanks a lot and let me know in case of any other issue ;)

**Comment by ktaneja** [comment]
Grazie Mille Myriam :)! I ran the test cases and the code works. I had a
question regarding the deployment.
How and on which server do you deploy the code to?

Thanks,
Kunal

**Comment by iammyr** [comment]
Hi Kunal,

apologies for the late reply: for some reason the email notifying me of your comment from GitHub ended up in the spam folder so I read it today only by chance!
I use the RESTlet library which provides "connectors" for the client and server sides . You can choose one of the server connectors listed at http://restlet.com/learn/guide/2.2/core/base/connectors/ by adding the corresponding jar to your classpath. I personally used the built-in server connector (called "Internal" http://restlet.com/learn/guide/2.2/core/engine/internal-connectors ) which was recommended for lightweight deployments. However, you could easily change that to use more advanced ones.

Then, you just create a jar of your own server and run it as a java server. 
You can find more info (also a link to an instance currently running online) at http://spitfire-project.eu/?q=ld4s

Please, do let me know in case of any other issue ;) I'll pay more attention to my spam folder as well.

Cheers,
Myriam

**Comment by ktaneja** [comment]
Thanks Myriam! I was able to deploy it on Apache Tomcat.I will let you know
if I have any more concerns.

Thanks,
Kunal
